Add meta device with inode in self copy check
Svetlitski/fcp pull request #30
Opened 2022-02-17 07:28 UTC by xychu

Combine dev number with inode to identifies a file uniquely,
since the same inode could be used at a different filesystem.

2022-02-27 23:04 UTC, Svetlitski requested changes
This is an interesting edge-case that I hadn't considered. Out of curiosity, did you get unlucky enough to actually encounter this while using `fcp`, or is it something that you just noticed while reading through the code?

2022-02-27 23:04 UTC, Svetlitski commented on src/lib.rs
> +        .map(|source| fs::symlink_metadata(source).map(|meta| format!("{}/{}", meta.dev().to_string(), meta.ino().to_string())))
```suggestion
        .map(|source| fs::symlink_metadata(source).map(unique_id)
```

2022-02-27 23:04 UTC, Svetlitski commented on src/lib.rs
> +    for (ancestor, dev_ino) in dest.ancestors().zip(ancestor_dev_inos) {
```suggestion
    for (ancestor, id) in dest.ancestors().zip(ancestor_ids) {
```

Again, change this variable name everywhere it occurs.

2022-02-27 23:04 UTC, Svetlitski commented on src/lib.rs
> +        for (source, source_dev_ino) in sources.iter().zip(source_dev_inos.as_ref()) {
```suggestion
        for (source, source_id) in sources.iter().zip(source_ids.as_ref()) {
```

Again with the variable name change.

2022-02-28 07:09 UTC, xychu commented
> This is an interesting edge-case that I hadn't considered. Out of curiosity, did you get unlucky enough to actually encounter this while using `fcp`, or is it something that you just noticed while reading through the code?

Got bitten when coping data from USB SSD deivce via  `fcp` :-(
And I'll update my code accordingly.

2022-03-05 23:29 UTC, Svetlitski commented
Thank you! I force-pushed just to fix a couple of spelling/phrasing issues in the comments instead of going through the hassle of flagging them in review and asking you to fix them. The failing test-case on CI is just the GitHub actions cache not working, so I'm going to merge this. Thanks for the contribution!

2022-03-05 23:29 UTC, merged